"""empty message

Revision ID: 50832f43b32a
Revises: c2992f6a1f66
Create Date: 2017-09-16 19:03:30.384608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50832f43b32a'
down_revision = 'c2992f6a1f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'holdings', ['torrent_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holdings', type_='unique')
    # ### end Alembic commands ###
