"""empty message

Revision ID: 9f531d6f929e
Revises: 
Create Date: 2017-05-02 22:23:23.792805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f531d6f929e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formats',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('physical', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stacks',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holding_groups',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('album_title', sa.String(), nullable=False),
    sa.Column('album_artist', sa.String(), nullable=False),
    sa.Column('releasegroup_mbid', postgresql.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stack_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('release_mbid', postgresql.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_desc', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('holding_group_id', postgresql.UUID(), nullable=False),
    sa.Column('format_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], ),
    sa.ForeignKeyConstraint(['holding_group_id'], ['holding_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotation_releases',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('bin', sa.String(), nullable=True),
    sa.Column('holding_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotation_releases')
    op.drop_table('holdings')
    op.drop_table('holding_groups')
    op.drop_table('stacks')
    op.drop_table('formats')
    # ### end Alembic commands ###
