"""empty message

Revision ID: ada8d0518991
Revises: 9f531d6f929e
Create Date: 2017-05-02 22:39:14.697213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada8d0518991'
down_revision = '9f531d6f929e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_comments',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('reviewer_username', sa.String(), nullable=True),
    sa.Column('reviewer_fullname', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('REVIEW', 'COMMENT', 'TRACK_WARNING', 'OTHER', name='holdingcommenttype'), nullable=False),
    sa.Column('holding_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holding_tags',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('holding_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('track_num', sa.Integer(), nullable=False),
    sa.Column('disc_num', sa.Integer(), nullable=False),
    sa.Column('track_mbid', postgresql.UUID(), nullable=True),
    sa.Column('recording_mbid', postgresql.UUID(), nullable=True),
    sa.Column('has_fcc', sa.Enum('YES', 'NO', 'UNKNOWN', name='trackfccstatus'), nullable=False),
    sa.Column('holding_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('holding_tags')
    op.drop_table('holding_comments')
    # ### end Alembic commands ###
