"""empty message

Revision ID: b5ffe385a562
Revises: ada8d0518991
Create Date: 2017-05-13 21:46:18.050149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5ffe385a562'
down_revision = 'ada8d0518991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_metadata',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('track_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_metadata')
    # ### end Alembic commands ###
