"""empty message

Revision ID: c2992f6a1f66
Revises: b5ffe385a562
Create Date: 2017-09-16 18:59:49.323458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2992f6a1f66'
down_revision = 'b5ffe385a562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('torrent_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'torrent_hash')
    # ### end Alembic commands ###
